# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Alejandro Amaral
email: hola@logico.com.ar
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://janoamaral.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: logico_ar
github_username: janoamaral

input: GFM

# Build settings
plugins:
  - jekyll-feed
  - jekyll-postcss
  - premonition
  - jekyll-octicons
host: 0.0.0.0

postcss:
  cache: false

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 10
paginate_path: "page:num"

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

premonition:
  types:
    important:
      meta:
        my-meta: "Test 3"
    custombox:
      meta:
        my-meta: "Test"
    advanced:
      template: "Liquid template goes here"
      default_title: "MY BLOCK"
      meta:
        my-meta: "By myself"
